idf_component_register(
    SRCS
        "main.c"
        "i2c_comm.c"
        "music_leds.c"
        "tft_ui.c"
        "speaker_music.c"
        "../../../shared_components/led_matrix/led_matrix.c"
        "../../../shared_components/status_strip/status_strip.c"
    INCLUDE_DIRS
        "."
        ".."
        "../.."
        "../../../include"
        "../../../shared_components/led_matrix"
        "../../../shared_components/status_strip"
    REQUIRES
        driver
        led_strip
        esp_lcd
        esp_timer
        lvgl
        espressif__arduino-esp32
        espressif__esp_lcd_ili9341
        atanisoft__esp_lcd_touch_xpt2046
        audio
        battery_monitor
        startup_guard
        led_matrix
    EMBED_FILES
        "audio/baby_shark.wav"
        "audio/be_alright.wav"
        "audio/espresso.wav"
        "audio/little_einsteins.wav"
        "audio/lush_life.wav"
        "audio/pink_pony.wav"
        "audio/no.wav"
        "audio/sofia_the_first.wav"
)

target_compile_definitions(${COMPONENT_LIB} PRIVATE LED_MATRIX_HAS_STATUS_STRIP)
