#ifndef LV_CONF_H
#define LV_CONF_H

/*
 * Minimal LVGL config for the Music Sequence block simulator (SDL).
 * LVGL fills in the rest from its internal defaults.
 */

#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_NONE

#define LV_USE_STDLIB_MALLOC  LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_STRING  LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_BUILTIN

#define LV_DEF_REFR_PERIOD 33
#define LV_DPI_DEF 130

#define LV_USE_DRAW_SW 1

#define LV_USE_SDL 1
#if LV_USE_SDL
    #define LV_SDL_INCLUDE_PATH <SDL.h>
    #define LV_SDL_RENDER_MODE LV_DISPLAY_RENDER_MODE_DIRECT
    #define LV_SDL_BUF_COUNT 1
    #define LV_SDL_ACCELERATED 1
    #define LV_SDL_FULLSCREEN 0
    #define LV_SDL_DIRECT_EXIT 1
    #define LV_SDL_MOUSEWHEEL_MODE LV_SDL_MOUSEWHEEL_MODE_ENCODER
#endif

#define LV_USE_FONT_MONTSERRAT_14 1
#define LV_USE_FONT_MONTSERRAT_16 1
#define LV_USE_FONT_MONTSERRAT_18 1
#define LV_USE_FONT_MONTSERRAT_20 1
#define LV_USE_FONT_MONTSERRAT_22 1
#define LV_USE_FONT_MONTSERRAT_24 1
#define LV_USE_FONT_MONTSERRAT_26 1

#define LV_USE_LABEL 1
#define LV_USE_BUTTON 1

#endif
